# SPDX-FileCopyrightText: 2025 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

# This is a reusable workflow to mirror a single branch from a remote git repository to GitHub.

name: Mirror remote repository to GitHub

on:
  workflow_call:
    inputs:
      repository-url:
        description: The HTTPS URL of the source git repository to clone to GitHub.
        type: string
        required: true
      rewrite-lfs:
        description: |
          Whether to convert Git LFS pointer files to their associated blob files, effectively disabling Git LFS in the mirror.
          By default, LFS will be included in the mirror repository.
          Be careful when enabling this option because it may increase the execution time of this workflow significantly.
          There are certain limits on GitHub so it is important to keep LFS disabled on some repositories.
        type: boolean
        required: false
        default: false
      rewrite-lfs-timeout:
        description: |
          The maximum number of minutes the Migrate LFS job step is allowed to run.
          Only takes effect if rewrite-lfs is set to true.
          The default value is 30 minutes.
        type: number
        required: false
        default: 30
    secrets:
      token:
        description: |
          The personal access token used to perform operations.
          Some permissions, such as `workflows`, are only available to PATs and not to the default GITHUB_TOKEN.
        required: false

jobs:
  mirror-remote-repo:
    runs-on: ubuntu-22.04
    env:
      GIT_LFS_VERSION: "3.6.1"
    steps:
      # Git LFS is moved to /usr/local/bin/ because we need our downloaded version to be executed
      # instead of the Git LFS version included with the Ubuntu image provided by GitHub.
      - name: Download and move Git LFS
        run: |
          wget https://github.com/git-lfs/git-lfs/releases/download/v${{ env.GIT_LFS_VERSION }}/git-lfs-linux-amd64-v${{ env.GIT_LFS_VERSION }}.tar.gz
          tar xzf git-lfs-linux-amd64-v${{ env.GIT_LFS_VERSION }}.tar.gz
          mv git-lfs-${{ env.GIT_LFS_VERSION }}/git-lfs /usr/local/bin/

      - name: Configure Git LFS
        run: git lfs install

      - name: Clone remote repository
        run: git clone --branch ${{ github.ref_name }} ${{ inputs.repository-url }} source

      # This will rewrite the git history, it will change the ID of most git objects in the mirror.
      - name: Migrate LFS
        if: ${{ inputs.rewrite-lfs }}
        working-directory: ./source
        timeout-minutes: ${{ inputs.rewrite-lfs-timeout }}
        run: |
          git lfs uninstall
          git lfs migrate export --verbose --include="*" --everything --skip-fetch --yes 2>&1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.token != '' && secrets.token || secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
          directory: source
