# SPDX-FileCopyrightText: 2025 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

# This is a reusable workflow intended to be called when a pull request is opened.

name: Decommission pull requests on GitHub

on:
  workflow_call:

jobs:
  close-pull-request:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
      COMMENT: |
        Thank you for your contribution to our project.

        Our repositories hosted on GitHub are merely a mirror, a backup of our main repositories on GitLab.

        Please, submit your contributions to the corresponding repository on GitLab:

        <https://gitlab.com/veloren/>

        That said, this pull request will be closed automatically.
    steps:
      - name: Close the pull request with a comment
        run: gh pr close "${PULL_REQUEST_URL}" --comment "${COMMENT}"
